# Generated by Django 3.1.3 on 2020-11-28 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AddField(
            model_name='articles',
            name='first_name',
            field=models.CharField(default='some_value', max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='articles',
            name='last_name',
            field=models.CharField(default='some_value', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='articles',
            name='mail',
            field=models.EmailField(default='@mail.ru', max_length=254),
        ),
        migrations.AddField(
            model_name='articles',
            name='phone',
            field=models.TextField(default='8900000000', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='textinteres',
            field=models.TextField(blank=True, verbose_name='Область научных интересов'),
        ),
        migrations.AddField(
            model_name='articles',
            name='textkeys',
            field=models.TextField(blank=True, verbose_name='Ключевые компетенции'),
        ),
        migrations.AddField(
            model_name='articles',
            name='textwork',
            field=models.TextField(blank=True, verbose_name='Предыдущий опыт'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец резюме'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
