# Generated by Django 3.1.3 on 2020-11-28 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201128_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstquetion', models.TextField(blank=True, verbose_name='Первый вопрос')),
                ('secondquetion', models.TextField(blank=True, verbose_name='Второй вопрос')),
                ('thirdquetion', models.TextField(blank=True, verbose_name='Третий вопрос')),
                ('fourquetion', models.TextField(blank=True, verbose_name='Четверый вопрос')),
                ('fivequetion', models.TextField(blank=True, verbose_name='Пятый вопрос')),
                ('sixquetion', models.TextField(blank=True, verbose_name='Шестой вопрос')),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='last_name',
            field=models.CharField(default='default_name', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Vacansy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='user')),
                ('last_name', models.CharField(default='default_name', max_length=200, verbose_name='Фамилия')),
                ('first_name', models.CharField(default='some_value', max_length=200, verbose_name='Имя')),
                ('phone', models.TextField(default='8900000000', max_length=12, unique=True)),
                ('mail', models.EmailField(default='@mail.ru', max_length=254)),
                ('text', models.TextField(verbose_name='Описание')),
                ('textinteres', models.TextField(blank=True, verbose_name='Область научных интересов')),
                ('textwork', models.TextField(blank=True, verbose_name='Предыдущий опыт')),
                ('textkeys', models.TextField(blank=True, verbose_name='Ключевые компетенции')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец резюме')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
